services:
    victoire_core.widget_date_content_resolver:
        class: Victoire\Widget\DateBundle\Resolver\WidgetDateContentResolver
        tags:
            - { name: victoire_widget.widget_content_resolver, alias: Date }

    victoire.widget.date:
        class: Victoire\Widget\DateBundle\Entity\WidgetDate

    victoire.widget.form.date:
        class: Victoire\Widget\DateBundle\Form\WidgetDateType
        arguments:
            - "%victoire_i18n.available_locales%"
        tags:
            - { name: form.type }
